> ### **Assignment 2 - Numpy Array Operations** 
>
> This assignment is part of the course ["Data Analysis with Python: Zero to Pandas"](http://zerotopandas.com). The objective of this assignment is to develop a solid understanding of Numpy array operations. In this assignment you will:
> 
> 1. Pick 5 interesting Numpy array functions by going through the documentation: https://numpy.org/doc/stable/reference/routines.html 
> 2. Run and modify this Jupyter notebook to illustrate their usage (some explanation and 3 examples for each function). Use your imagination to come up with interesting and unique examples.
> 3. Upload this notebook to your Jovian profile using `jovian.commit` and make a submission here: https://jovian.ml/learn/data-analysis-with-python-zero-to-pandas/assignment/assignment-2-numpy-array-operations
> 4. (Optional) Share your notebook online (on Twitter, LinkedIn, Facebook) and on the community forum thread: https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575 . 
> 5. (Optional) Check out the notebooks [shared by other participants](https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575) and give feedback & appreciation.
>
> The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.
>
> Try to give your notebook a catchy title & subtitle e.g. "All about Numpy array operations", "5 Numpy functions you didn't know you needed", "A beginner's guide to broadcasting in Numpy", "Interesting ways to create Numpy arrays", "Trigonometic functions in Numpy", "How to use Python for Linear Algebra" etc.
>
> **NOTE**: Remove this block of explanation text before submitting or sharing your notebook online - to make it more presentable.


# Title Here


### Subtitle Here

Write a short introduction about Numpy and list the chosen functions. 

- function 1
- function 2
- function 3
- function 4
- function 5

The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.

In [1]:
!pip install jovian --upgrade -q

In [2]:
import jovian

In [3]:
jovian.commit(project='numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Updating notebook "mirajahmedsymanto/numpy-array-operations" on https://jovian.com
[jovian] Committed successfully! https://jovian.com/mirajahmedsymanto/numpy-array-operations


'https://jovian.com/mirajahmedsymanto/numpy-array-operations'

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [4]:
import numpy as np

In [5]:
# List of functions explained 
function1 = np.unique
function2 = np.arrange
function3 = np.random.randint
function4 = np.corrcoef
function5 = np.mean

## Function 1 - np.unique.
The np.unique() function is used to find the unique elements of an array and return the sorted unique elements.


In [6]:
# Example 1 - 1D array

arr = np.array([1, 2, 2, 3, 4, 4, 4, 5])
unique_elements = np.unique(arr)

print("Original array: ", arr)
print("Unique elements: ", unique_elements)


Original array:  [1 2 2 3 4 4 4 5]
Unique elements:  [1 2 3 4 5]


The above two arrays consist of similar elements. However, the second array only shows the elements once avoiding the repetition of elements because of the unique() function. 

In [7]:
# Example 2 - 2D array

arr = np.array([[1, 2, 3], [2, 3, 4], [3, 4, 5]])
unique_elements = np.unique(arr)

print("Original array: \n", arr)
print("Unique elements: \n", unique_elements)

Original array: 
 [[1 2 3]
 [2 3 4]
 [3 4 5]]
Unique elements: 
 [1 2 3 4 5]


The above two 2D arrays consist of similar elements. However, the second array only shows the elements once avoiding the repetition of elements because of the unique() function in a 1D array. 

In [10]:
# Example 3 - breaking (TypeError)

a = np.array([1, 2, 3, 2, 'a', 'b', 'a'], dtype=object)
np.unique(a)

TypeError: '<' not supported between instances of 'str' and 'int'

In this case, the input array a has elements of different data types, including integers and strings. The np.unique function will still work, but the output will be of dtype object, as it can handle elements of different data types. The output is the sorted unique elements of the input array, including both integers and strings. To fix this, you can explicitly cast the input array a to a homogeneous data type before passing it to the np.unique function.

a = np.array([1, 2, 3, 2, 'a', 'b', 'a'], dtype=object)
a = np.array(a, dtype=str)
np.unique(a)

In [23]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/aakashns/numpy-array-operations


'https://jovian.ml/aakashns/numpy-array-operations'

## Function 2 - np.arange

np.arange generates evenly spaced values within a given interval. It's similar to the range function in Python, but it returns a numpy array instead of a list.

In [11]:
# Example 1 - working
a = np.arange(0, 10, 2)
print(a)

[0 1 2 3 4 5 6 7 8 9]


Generate an array of numbers from 0 to 9 with step 2

In [ ]:
# Example 2 - working
a = np.arange(27).reshape(3, 3, 3)
print(a)

Generate an array of size (3,3,3) with numbers from 0 to 26 with the help of both arange and reshape functions. However, highlight function here is arange.

In [12]:
# Example 3 - breaking 

def my_function(x):
    a = np.array([1, 2, 3, 4])
    return a + x

inputs = np.array([[1, 2, 3], [4, 5, 6]])
output = np.array([])

for i in range(inputs.shape[0]):
    output = np.append(output, my_function(inputs[i]))

print(output)





ValueError: operands could not be broadcast together with shapes (4,) (3,) 

The error is occurring because np.append is used to append elements to an existing array, but output is not initialized as a numpy array with a specific shape. When np.append is called for the first time with output as an empty numpy array, it does not have a shape, so it cannot be appended to. This results in a ValueError.

To fix this error, initialize output as a numpy array with the desired shape and data type before using np.append

In [13]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "mirajahmedsymanto/numpy-array-operations" on https://jovian.com
[jovian] Committed successfully! https://jovian.com/mirajahmedsymanto/numpy-array-operations


'https://jovian.com/mirajahmedsymanto/numpy-array-operations'

## Function 3 - random.randint

np.random.randint generates random integers from low (inclusive) to high (exclusive) for a given shape.

In [ ]:
# Example 1 - working
a = np.random.randint(0, 10, size=(3,3))
print(a)

Generate a 2D array of shape (3,3) with random integers from 0 to 9

In [ ]:
# Example 2 - working
a = np.random.randint(0, 10, size=(2,2,2))
print(a)

Generate a 3D array of shape (2,2,2) with random integers from 0 to 9

In [22]:
# Example 3 - breaking (to illustrate when it breaks)

rand_num = np.random.randint(size=(3,3))
print(rand_num)



TypeError: randint() takes at least 1 positional argument (0 given)

This code generates an error because numpy.random.randint requires at least one argument, the high value (inclusive), which determines the range of random integers to generate. In the code above, no high value is provided, so the function raises a TypeError

To resolve this error, we need to provide the high value.

In [23]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "mirajahmedsymanto/numpy-array-operations" on https://jovian.com
[jovian] Committed successfully! https://jovian.com/mirajahmedsymanto/numpy-array-operations


'https://jovian.com/mirajahmedsymanto/numpy-array-operations'

## Function 4 - np.corrcoef

np.corrcoef calculates the correlation coefficient between two arrays or between the columns of a 2D array. The correlation coefficient is a value between -1 and 1 that indicates the strength and direction of a linear relationship between two variables.

In [24]:
# Example 1 - working

a = np.array([[1, 2, 3, 4, 5], [5, 4, 3, 2, 1]])
r = np.corrcoef(a)
print(r)

[[ 1. -1.]
 [-1.  1.]]


Calculate the correlation coefficient between columns of a 2D array

In [31]:
# Example 2 - working

a = np.array([[1, 2, 3, 4, 5], [5, 4, 3, 2, 1], [2, 3, 4, 5, 6]])
r = np.corrcoef(a)
print(r)

[[ 1. -1.  1.]
 [-1.  1. -1.]
 [ 1. -1.  1.]]


Explanation about example

In [32]:
# Example 3 - breaking
data = np.random.randint(10, size=(3,3,3))
correlation = np.corrcoef(data)
print(correlation)

ValueError: m has more than 2 dimensions

np.corrcoef only accepts two-dimensional arrays, but data has 3 dimensions. The ValueError message "m has more than 2 dimensions" indicates that the input has more than 2 dimensions.

To resolve this error, we need to reduce the dimensions of data to 2

In [33]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "mirajahmedsymanto/numpy-array-operations" on https://jovian.com
[jovian] Committed successfully! https://jovian.com/mirajahmedsymanto/numpy-array-operations


'https://jovian.com/mirajahmedsymanto/numpy-array-operations'

## Function 5 - np.mean

np.mean is a function in the NumPy library that calculates the mean of a given array. The mean is the sum of all elements divided by the number of elements.

In [34]:
# Example 1 - working
a = np.array([[1, 2, 3, 4, 5], [5, 4, 3, 2, 1]])
mean = np.mean(a, axis=0)
print(mean)

[3. 3. 3. 3. 3.]


Calculate the mean of a 2D array along a specific axis

In [36]:
# Example 2 - working
a = np.array([
    [
        [1, 2, 3, 4, 5], 
        [5, 4, 3, 2, 1]
    ], 
    [
        [2, 3, 4, 5, 6], 
        [6, 5, 4, 3, 2]
    ]
])
mean = np.mean(a, axis=(0, 2))
print(mean)

[3.5 3.5]


a is a 3D array with shape (2, 2, 5). The axis argument is set to (0, 2) so that the mean is calculated along the first and third dimensions, leaving a 2D array with shape (2, 1). The resulting array contains the mean values of the first and second sub-arrays of a along the third dimension (the axis with length 5)

In [38]:
# Example 3 - breaking (to illustrate when it breaks)
a = [1, 2, 3, 4, 5]
mean = np.mean(a, axis=1)
print(mean)

AxisError: axis 1 is out of bounds for array of dimension 1

 np.mean only accepts arrays, not lists.

To resolve this error, we need to convert 'a' to a numpy array

In [39]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "mirajahmedsymanto/numpy-array-operations" on https://jovian.com
[jovian] Committed successfully! https://jovian.com/mirajahmedsymanto/numpy-array-operations


'https://jovian.com/mirajahmedsymanto/numpy-array-operations'

## Conclusion

Summarize what was covered in this notebook, and where to go next

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* ...

In [40]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "mirajahmedsymanto/numpy-array-operations" on https://jovian.com
[jovian] Committed successfully! https://jovian.com/mirajahmedsymanto/numpy-array-operations


'https://jovian.com/mirajahmedsymanto/numpy-array-operations'